site_name: Gestion de courses (FFCK)
site_author: Bastien BOYER
copyright: Copyright 2023, Bastien BOYER, FFCK CNA CEL

theme:
  name: mkdocs
  highlightjs: true
  locale: fr
  prev_next_buttons_location: none
  titles_only: true

plugins:
  - search
  
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
