site_name: Gestion de courses
site_url: https://gestion-de-courses.readthedocs.io
site_author: Bastien BOYER
copyright: Copyright 2023, Bastien BOYER, FFCK CNA CEL

theme:
  name: readthedocs
  highlightjs: true
  locale: fr
  navigation_depth: 3

plugins:
  - search
  
markdown_extensions:
  - markdown_include.include:
      base_path: ./docs
  - admonition
  - kbdextension
  - attr_list
  - pymdownx.mark

nav:
  - Général:
    - Organisation: 'general/organisation.md'
    - Téléchargements: 'general/telechargements.md'
    - À propos de nous: 'general/a-propos.md'
  - 4D:
    - Présentation: '4d/presentation.md'
    - Gérer les inscriptions: '4d/gestion-inscription.md'
    - Créer un programme: '4d/creation-programme.md'
    - Gérer une compétition: '4d/gestion-competition.md'
    - Résultats en live: '4d/resultat-live.md'
  - CompetFFCK:
    - Présentation: 'competffck/presentation.md'
    - Créer une compétition: 'competffck/creer-competition.md'
    - Gérer les inscriptions: 'competffck/gestion-inscription.md'
    - Utilisation avancée: 'competffck/utilisation-avancee.md'
  - Lynx: 
    - Présentation: 'lynx/presentation.md'
    - Chronométrage: 'lynx/chronometrage.md'
    - Installation: 'lynx/installation.md'
    - Résultats en live: 'lynx/resultat-live.md'
  - MariTime:
    - Présentation: 'maritime/presentation.md'
    - Chronométrage: 'maritime/chronometrage.md'
    - Installation: 'maritime/installation.md'
  - ChronoPC: 
    - Présentation: 'chronopc/presentation.md'
    - Chronométrage: 'chronopc/chronometrage.md'
    - Installation: 'chronopc/installation.md'
