site_name: Gestion de courses
site_url: https://gestion-de-courses.readthedocs.io
site_author: Bastien BOYER
copyright: Copyright 2023, Bastien BOYER, FFCK CNA CEL

theme:
  name: mkdocs
  highlightjs: true
  locale: fr
  prev_next_buttons_location: none

plugins:
  - search
  
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - 4D: '4d/presentation.md'
  - CompetFFCK: 'competffck/presentation.md'
  - Lynx: 'lynx/presentation.md'
  - MariTime: 'maritime/presentation.md'
  - ChronoPC:  'chronopc/presentation.md'